#Spell:words alacritty lfcd
live_config_reload: true

env:
    TERM: xterm-256color

import:
    - ~/.config/alacritty/aw/current.yml

selection:
    semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
    save_to_clipboard: true

window:
    dimensions:
        columns: 156
        lines: 62
    opacity: 0.94
    padding:
        x: 12
        y: 12
    dynamic_padding: false
    decorations: buttonless

mouse:
    hide_when_typing: true

scrolling:
    history: 10000

font:
    normal:
        family:
            FiraCode Nerd Font Mono
            #style: Regular

    bold:
        family: FiraCode Nerd Font Mono
        #style: Bold

    italic:
        family: FiraCode Nerd Font Mono
        #style: Italic

    #bold_italic:
    #family: monospace
    #style: Bold Italic

    size: 13

    offset:
        x: 2
        y: 4

    use_thin_strokes: true

colors:
    # Default colors
    primary:
        background: '0x272822'
        foreground: '0xf8f8f2'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
        text: '0x272822'
        cursor: '0xf8f8f2'

    # Normal colors
    normal:
        black: '0x272822'
        red: '0xf92672'
        green: '0xa6e22e'
        yellow: '0xf4bf75'
        blue: '0x66d9ef'
        magenta: '0xae81ff'
        cyan: '0xa1efe4'
        white: '0xf8f8f2'

    # Bright colors
    bright:
        black: '0x75715e'
        red: '0xf92672'
        green: '0xa6e22e'
        yellow: '0xf4bf75'
        blue: '0x66d9ef'
        magenta: '0xae81ff'
        cyan: '0xa1efe4'
        white: '0xf9f8f5'

    indexed_colors:
        - { index: 16, color: '0xfd971f' }
        - { index: 17, color: '0xcc6633' }
        - { index: 18, color: '0x383830' }
        - { index: 19, color: '0x49483e' }
        - { index: 20, color: '0xa59f85' }
        - { index: 21, color: '0xf5f4f1' }

key_bindings:
    - { key: Comma, mods: Command, chars: "\x02," }
    - { key: D, mods: Command, chars: "\x02K" }
    - { key: F, mods: Command, chars: "lfcd\n" }
    - { key: G, mods: Command, chars: "\x02g" }
    - { key: L, mods: Command, chars: "\x02L" }
    # - { key: K, mods: Command, chars: "\x02s" }
    - { key: E, mods: Command|Shift, chars: "\x02%" }
    - { key: E, mods: Command, chars: "\x02\"" }
    - { key: Q, mods: Command, chars: ":q\n" }
    - { key: S, mods: Command, chars: ":w\n" }
    - { key: S, mods: Command|Shift, chars: ":wa\n" }
    - { key: T, mods: Command, chars: "\x02c" }
    - { key: J, mods: Command, chars: "\x02\x54" }
    - { key: W, mods: Command, chars: "\x02x" }
    - { key: Z, mods: Command, chars: "\x02z" }
    - { key: K, mods: Command, chars: "clear\x0a" }
    - { key: D, mods: Option, chars: "cd ~/Developer/projects/\x0a" }
    - { key: Key1, mods: Command, chars: "\x021" }
    - { key: Key2, mods: Command, chars: "\x022" }
    - { key: Key3, mods: Command, chars: "\x023" }
    - { key: Key4, mods: Command, chars: "\x024" }
    - { key: Key5, mods: Command, chars: "\x025" }
    - { key: Key6, mods: Command, chars: "\x026" }
    - { key: Key7, mods: Command, chars: "\x027" }
    - { key: Key8, mods: Command, chars: "\x028" }
    - { key: Key9, mods: Command, chars: "\x029" }
    - { key: LBracket, mods: Command, chars: "\x02[" }
    - { key: LBracket, mods: Command|Shift, chars: "\x02p" }
    - { key: RBracket, mods: Command|Shift, chars: "\x02n" }
    - { key: Semicolon, mods: Command, chars: "\x02:" }
