add_newline = false

format = """\
  $username\
  $memory_usage\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $package\
  $rust\
  $nodejs\
  $deno\
  $nix_shell\
  $env_var\
  $line_break\
  $battery\
  $cmd_duration\
  $jobs\
  $time\
  $character\
  """

[line_break]
disabled = true

[character]
# symbol = "➜"
error_symbol = "✗"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style) || "
trim_at = "."
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[git_status]
conflicted = " ⚔ "
ahead = "⇡{$count}"
behind = "⇣{$count}"
diverged = "⇕"
up_to_date = ""
untracked = "?{$count}"
stashed = "$"
modified = "!{$count}"
staged = "+{$count}"
renamed = "»{$count}"
deleted = "✘{$count}"
style = "bold red"
