#                                     ╭─────╮
#                                     │ sys │
#                                     ╰─────╯

add_newline = false

[line_break]
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
min_time = 10_000                    # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 128
truncate_to_repo = false
style = " blue"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 80
style = "bold dimmed white"
disabled = false

[git_branch]
symbol = "🌱 "

[git_status]
conflicted = "⚔ "
ahead = "⇡{$count} "
behind = "⇣{$count} "
diverged = "⇕ "
up_to_date = ""
untracked = "?{$count} "
stashed = "$ "
modified = "!{$count} "
staged = "+{$count} "
renamed = "»{$count} "
deleted = "✘{$count} "
style = "bold red"
