add_newline = false

format = """\
  $username\
  $memory_usage\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $package\
  $rust\
  $nodejs\
  $deno\
  $env_var\
  $line_break\
  $battery\
  $cmd_duration\
  $jobs\
  $time\
  $character\
  """

[line_break]
disabled = true

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[hostname]
ssh_only = false
format = "[$hostname]($style) || "
trim_at = "."
disabled = false

[directory]
truncation_length = 64
format = "[$path]($style)[$read_only]($read_only_style) | "
truncate_to_repo = false
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
conflicted = " ⚔ "
ahead = "⇡{$count}"
behind = "⇣{$count}"
diverged = "⇕"
up_to_date = ""
untracked = "?{$count}"
stashed = "$"
modified = "!{$count}"
staged = "+{$count}"
renamed = "»{$count}"
deleted = "✘{$count}"
style = "bold red"
