live_config_reload = true
import = [
    "~/Developer/mmc/.config/alacritty/themes/catppuccin/catppuccin-mocha.yml",
]

[env]
TERM = "xterm-256color"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[window]
opacity = 0.7
dynamic_padding = false
decorations = "buttonless"

[window.dimensions]
columns = 512
lines = 128

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 5_120

[font]
size = 18

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 2

[keyboard]
    # { key=" Key9", mods= "Command", chars= "\x02\x39" },
# bindings = [
#     { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
#     { key = "L", mods = "Control|Shift", chars = "l" },
#
#     # rename: ^B,
#     { key= "Comma", mods= "Command", chars= "\u0002\u2c" },
#     { key= "Comma", mods= "Command|Shift", chars= "\x02\x24" },
#
#     # Switch to last tmux session= ^B$
#     { key= "L", mods= "Command", chars= "\x02\x73" },
#
#     # Change to the previous tmux window= ^Bs
#     { key=" LBracket", mods= "Command|Shift", chars= "\x02\x70" },
#     # Change to the next tmux window= ^Bp
#     { key=" RBracket", mods= "Command|Shift", chars= "\x02\x6e" },
#
#     # Split the current pane into two, left and right= ^Bn
#     { key=" N", mods= "Command|Shift", chars= "\x02\x25" },
#     # Split the current pane into two, top and bottom. ^B%
#     { key=" N", mods= "Command", chars= "\x02\x22" },
#
#     # Kill the current tmux pane (and window if last pane) ^B"
#     { key=" W", mods= "Command", chars= "\x02\x78" },
#     # Detach the current tmux client ^Bx
#     { key=" Q", mods= "Control", chars= "\x02\x64" },
#
#     # Create a new tmux window ^Bd
#     { key=" T", mods= "Command", chars= "\x02\x63" },
#     # Break the current tmux pane out of the tmux window ^Bc
#     # - { key= T, mods= Command|Shift, chars= "\x02\x21" }
#
#     # Toggle the zoom state of the current tmux pane ^Bz
#     { key=" Z", mods= "Command", chars= "\x02\x7a" },
#
#     # Select window 1-9 ^B1 ^B2 ^B3 ^B4 ^B5 ^B6 ^B7 ^B8 ^B9
#     { key=" Key1", mods= "Command", chars= "\x02\x31" },
#     { key=" Key2", mods= "Command", chars= "\x02\x32" },
#     { key=" Key3", mods= "Command", chars= "\x02\x33" },
#     { key=" Key4", mods= "Command", chars= "\x02\x34" },
#     { key=" Key5", mods= "Command", chars= "\x02\x35" },
#     { key=" Key6", mods= "Command", chars= "\x02\x36" },
#     { key=" Key7", mods= "Command", chars= "\x02\x37" },
#     { key=" Key8", mods= "Command", chars= "\x02\x38" },
#
#     # Vim mode
[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
action = "ToggleViMode"
# ]

[[keyboard.bindings]]
key = "Comma"
mods = "Command"
chars = "\u0002,"

[[keyboard.bindings]]
key = "Comma"
mods = "Command|Shift"
chars = "\u0002$"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u0002s"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command|Shift"
chars = "\u0002p"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command|Shift"
chars = "\u0002n"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
chars = "\u0002\""

[[keyboard.bindings]]
key = "N"
mods = "Command"
chars = "\u0002%"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0002x"

[[keyboard.bindings]]
key = "Q"
mods = "Control"
chars = "\u0002d"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002c"

[[keyboard.bindings]]
key = "Z"
mods = "Command"
chars = "\u0002z"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u00021"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u00022"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u00023"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u00024"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u00025"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u00026"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u00027"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u00028"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u00029"

[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
action = "ToggleViMode"
